"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper
from notion.exceptions.api_exception import (
    ApiException,
)


class ErrorException(ApiException):
    def __init__(self, reason, response):
        """Initialize ErrorException object.

        Args:
            reason (string): The reason (or error message) for the Exception
                to be raised.
            response (HttpResponse): The HttpResponse of the API call.

        """
        super(ErrorException, self).__init__(reason, response)
        dictionary = APIHelper.json_deserialize(self.response.text)
        if isinstance(dictionary, dict):
            self.unbox(dictionary)

    def unbox(self, dictionary):
        """Populate the properties of this object by extracting them from a dictionary.

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        """
        self.object =\
            dictionary.get("object")\
            if dictionary.get("object")\
                else None
        self.status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else None
        self.code =\
            dictionary.get("code")\
            if dictionary.get("code")\
                else None
        self.message =\
            dictionary.get("message")\
            if dictionary.get("message")\
                else None
        self.request_id =\
            dictionary.get("request_id")\
            if dictionary.get("request_id")\
                else None


    def __str__(self):
        """Return a human-readable string representation."""
        _object=self.object
        _status=self.status
        _code=self.code
        _message=self.message
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _base_str = super().__str__()
        _base_str = _base_str[_base_str.find("(") + 1:-1]
        return (
            f"{self.__class__.__name__}("
            f"base_str={_base_str!s}, "
            f"object={_object!s}, "
            f"status={_status!s}, "
            f"code={_code!s}, "
            f"message={_message!s}, "
            f"request_id={_request_id!s}, "
            f")"
        )
