"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from apimatic_core.configurations.global_configuration import (
    GlobalConfiguration,
)
from apimatic_core.decorators.lazy_property import (
    LazyProperty,
)

from notion.apis.base_api import BaseApi
from notion.apis.blocks_api import BlocksApi
from notion.apis.comments_api import CommentsApi
from notion.apis.databases_api import DatabasesApi
from notion.apis.pages_api import PagesApi
from notion.apis.search_api import SearchApi
from notion.apis.users_api import UsersApi
from notion.configuration import (
    Configuration,
    Environment,
)
from notion.http.auth.oauth_2 import Oauth2


class NotionClient(object):
    """Client that provide access to the NotionClient APIs."""

    @LazyProperty
    def blocks(self):
        """Provide access to the BlocksApi endpoints."""
        return BlocksApi(self.global_configuration)

    @LazyProperty
    def comments(self):
        """Provide access to the CommentsApi endpoints."""
        return CommentsApi(self.global_configuration)

    @LazyProperty
    def databases(self):
        """Provide access to the DatabasesApi endpoints."""
        return DatabasesApi(self.global_configuration)

    @LazyProperty
    def pages(self):
        """Provide access to the PagesApi endpoints."""
        return PagesApi(self.global_configuration)

    @LazyProperty
    def search(self):
        """Provide access to the SearchApi endpoints."""
        return SearchApi(self.global_configuration)

    @LazyProperty
    def users(self):
        """Provide access to the UsersApi endpoints."""
        return UsersApi(self.global_configuration)

    def __init__(self, http_client_instance=None,
                 override_http_client_configuration=False, http_call_back=None,
                 timeout=30, max_retries=0, backoff_factor=2,
                 retry_statuses=None, retry_methods=None, proxy_settings=None,
                 logging_configuration=None, environment=Environment.PRODUCTION,
                 bearer_auth_credentials=None, config=None):
        """Initialize a new instance of NotionClient."""
        self.config = config or Configuration(
            http_client_instance=http_client_instance,
            override_http_client_configuration=override_http_client_configuration,
            http_call_back=http_call_back, timeout=timeout,
            max_retries=max_retries, backoff_factor=backoff_factor,
            retry_statuses=retry_statuses, retry_methods=retry_methods,
            proxy_settings=proxy_settings,
            logging_configuration=logging_configuration,
            environment=environment,
            bearer_auth_credentials=bearer_auth_credentials)

        self.global_configuration = GlobalConfiguration(self.config)\
            .global_errors(BaseApi.global_errors())\
            .base_uri_executor(self.config.get_base_uri)\
            .user_agent(BaseApi.user_agent(),
                BaseApi.user_agent_parameters())

        self.auth_managers = {
            "bearerAuth": Oauth2(self.config.bearer_auth_credentials),
        }
        self.global_configuration =\
            self.global_configuration.auth_managers(self.auth_managers)

    @classmethod
    def from_environment(cls, dotenv_path=None, **overrides):
        """Create a client instance using environment variables.

        Returns:
            NotionClient instance.

        """
        return cls(config=Configuration
            .from_environment(dotenv_path=dotenv_path, **overrides))
