"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from notion.api_helper import APIHelper
from notion.apis.base_api import BaseApi
from notion.configuration import Server
from notion.exceptions.error_exception import (
    ErrorException,
)
from notion.http.http_method_enum import HttpMethodEnum
from notion.models.comment import Comment
from notion.models.paginated_list import PaginatedList


class CommentsApi(BaseApi):
    """A Controller to access Endpoints in the notion API."""

    def __init__(self, config):
        """Initialize CommentsApi object."""
        super(CommentsApi, self).__init__(config)

    def list_comments(self,
                      notion_version,
                      block_id,
                      start_cursor=None,
                      page_size=None):
        """Perform a GET request to /comments.

        Retrieves a list of unresolved comments from a page or block. Requires the
        integration to have read comment capabilities.

        Args:
            notion_version (str): The version of the Notion API to use. The current
                version is 2022-06-28. This header is required for all API requests.
            block_id (uuid|str): The ID of the block or page to retrieve comments for.
            start_cursor (str, optional): Pagination cursor to continue fetching
                results.
            page_size (int, optional): Maximum number of comments to return (max 100).

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Comments successfully
                retrieved.

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/comments")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Notion-Version")
                .value(notion_version)
                .is_required(True))
            .query_param(Parameter()
                .key("block_id")
                .value(block_id)
                .is_required(True))
            .query_param(Parameter()
                .key("start_cursor")
                .value(start_cursor))
            .query_param(Parameter()
                .key("page_size")
                .value(page_size))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("bearerAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(PaginatedList.from_dictionary)
            .is_api_response(True)
            .local_error("401",
                "The bearer token is missing, invalid, or the integration lacks acces"
                "s.",
                ErrorException)
            .local_error("404",
                "The requested resource does not exist or the integration lacks acces"
                "s to it.",
                ErrorException)
            .local_error("429",
                "The request has been rate limited. Notion enforces rate limits of 3 "
                "requests per second for integrations. Retry after the specified dela"
                "y.",
                ErrorException),
        ).execute()

    def create_comment(self,
                       notion_version,
                       body):
        """Perform a POST request to /comments.

        Creates a comment on a page or in an existing discussion thread. The
        integration must have comment capabilities to use this endpoint.

        Args:
            notion_version (str): The version of the Notion API to use. The current
                version is 2022-06-28. This header is required for all API requests.
            body (CommentsRequest): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Comment successfully
                created.

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/comments")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("Notion-Version")
                .value(notion_version)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body)
                .is_required(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single("bearerAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(Comment.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request was invalid or malformed.",
                ErrorException)
            .local_error("401",
                "The bearer token is missing, invalid, or the integration lacks acces"
                "s.",
                ErrorException)
            .local_error("404",
                "The requested resource does not exist or the integration lacks acces"
                "s to it.",
                ErrorException)
            .local_error("429",
                "The request has been rate limited. Notion enforces rate limits of 3 "
                "requests per second for integrations. Retry after the specified dela"
                "y.",
                ErrorException),
        ).execute()
