"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from notion.api_helper import APIHelper
from notion.apis.base_api import BaseApi
from notion.configuration import Server
from notion.exceptions.error_exception import (
    ErrorException,
)
from notion.http.http_method_enum import HttpMethodEnum
from notion.models.paginated_list import PaginatedList


class SearchApi(BaseApi):
    """A Controller to access Endpoints in the notion API."""

    def __init__(self, config):
        """Initialize SearchApi object."""
        super(SearchApi, self).__init__(config)

    def search(self,
               notion_version,
               body=None):
        """Perform a POST request to /search.

        Searches all parent or child pages and databases that have been shared with
        an integration. Returns results based on the query, filter, and sort
        parameters. Results are sorted by relevance by default but can be sorted by
        last_edited_time. The search indexing may not be immediate, so recently
        created or updated objects may not appear right away.

        Args:
            notion_version (str): The version of the Notion API to use. The current
                version is 2022-06-28. This header is required for all API requests.
            body (SearchRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Search results
                successfully returned.

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/search")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("Notion-Version")
                .value(notion_version)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single("bearerAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(PaginatedList.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request was invalid or malformed.",
                ErrorException)
            .local_error("401",
                "The bearer token is missing, invalid, or the integration lacks acces"
                "s.",
                ErrorException)
            .local_error("429",
                "The request has been rate limited. Notion enforces rate limits of 3 "
                "requests per second for integrations. Retry after the specified dela"
                "y.",
                ErrorException),
        ).execute()
