"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper


class Annotations(object):
    """Implementation of the 'Annotations' model.

    Styling annotations applied to the text.

    Attributes:
        bold (bool): Whether the text is bold.
        italic (bool): Whether the text is italic.
        strikethrough (bool): Whether the text has a strikethrough.
        underline (bool): Whether the text is underlined.
        code (bool): Whether the text is formatted as inline code.
        color (str): The color of the text. Possible values include default, gray,
            brown, orange, yellow, green, blue, purple, pink, red, and their
            background variants (e.g., gray_background).
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "bold": "bold",
        "italic": "italic",
        "strikethrough": "strikethrough",
        "underline": "underline",
        "code": "code",
        "color": "color",
    }

    _optionals = [
        "bold",
        "italic",
        "strikethrough",
        "underline",
        "code",
        "color",
    ]

    def __init__(
        self,
        bold=APIHelper.SKIP,
        italic=APIHelper.SKIP,
        strikethrough=APIHelper.SKIP,
        underline=APIHelper.SKIP,
        code=APIHelper.SKIP,
        color=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Annotations instance."""
        # Initialize members of the class
        if bold is not APIHelper.SKIP:
            self.bold = bold
        if italic is not APIHelper.SKIP:
            self.italic = italic
        if strikethrough is not APIHelper.SKIP:
            self.strikethrough = strikethrough
        if underline is not APIHelper.SKIP:
            self.underline = underline
        if code is not APIHelper.SKIP:
            self.code = code
        if color is not APIHelper.SKIP:
            self.color = color

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        bold =\
            dictionary.get("bold")\
            if "bold" in dictionary.keys()\
                else APIHelper.SKIP
        italic =\
            dictionary.get("italic")\
            if "italic" in dictionary.keys()\
                else APIHelper.SKIP
        strikethrough =\
            dictionary.get("strikethrough")\
            if "strikethrough" in dictionary.keys()\
                else APIHelper.SKIP
        underline =\
            dictionary.get("underline")\
            if "underline" in dictionary.keys()\
                else APIHelper.SKIP
        code =\
            dictionary.get("code")\
            if "code" in dictionary.keys()\
                else APIHelper.SKIP
        color =\
            dictionary.get("color")\
            if dictionary.get("color")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(bold,
                   italic,
                   strikethrough,
                   underline,
                   code,
                   color,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _bold=(
            self.bold
            if hasattr(self, "bold")
            else None
        )
        _italic=(
            self.italic
            if hasattr(self, "italic")
            else None
        )
        _strikethrough=(
            self.strikethrough
            if hasattr(self, "strikethrough")
            else None
        )
        _underline=(
            self.underline
            if hasattr(self, "underline")
            else None
        )
        _code=(
            self.code
            if hasattr(self, "code")
            else None
        )
        _color=(
            self.color
            if hasattr(self, "color")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"bold={_bold!r}, "
            f"italic={_italic!r}, "
            f"strikethrough={_strikethrough!r}, "
            f"underline={_underline!r}, "
            f"code={_code!r}, "
            f"color={_color!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _bold=(
            self.bold
            if hasattr(self, "bold")
            else None
        )
        _italic=(
            self.italic
            if hasattr(self, "italic")
            else None
        )
        _strikethrough=(
            self.strikethrough
            if hasattr(self, "strikethrough")
            else None
        )
        _underline=(
            self.underline
            if hasattr(self, "underline")
            else None
        )
        _code=(
            self.code
            if hasattr(self, "code")
            else None
        )
        _color=(
            self.color
            if hasattr(self, "color")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"bold={_bold!s}, "
            f"italic={_italic!s}, "
            f"strikethrough={_strikethrough!s}, "
            f"underline={_underline!s}, "
            f"code={_code!s}, "
            f"color={_color!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
