"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper


class BlocksRequest(object):
    """Implementation of the 'Blocks Request' model.

    Block type-specific content to update. Include the block type key with the fields
    to modify.

    Attributes:
        archived (bool): Set to true to archive the block.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "archived": "archived",
    }

    _optionals = [
        "archived",
    ]

    def __init__(
        self,
        archived=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a BlocksRequest instance."""
        # Initialize members of the class
        if archived is not APIHelper.SKIP:
            self.archived = archived

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        archived =\
            dictionary.get("archived")\
            if "archived" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(archived,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _archived=(
            self.archived
            if hasattr(self, "archived")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"archived={_archived!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _archived=(
            self.archived
            if hasattr(self, "archived")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"archived={_archived!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
