"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper
from notion.models.object_1 import Object1
from notion.models.parent import Parent
from notion.models.partial_user import PartialUser
from notion.models.type_1 import Type1


class Block(object):
    """Implementation of the 'Block' model.

    A Block object represents a piece of content within a Notion page. Blocks are the
    building blocks of all page content and can be of many types including
    paragraphs, headings, lists, images, code, tables, and more. Blocks can contain
    other blocks as children, forming a tree structure.

    Attributes:
        object (Object1): Always "block" for block objects.
        id (uuid|str): Unique identifier for the block.
        parent (Parent): A Parent object represents the parent of a page, database,
            or block. The parent can be a workspace, page, database, or block.
        mtype (Type1): The type of block. Determines which type-specific content
            field is present. Common types include paragraph, heading_1, heading_2,
            heading_3, bulleted_list_item, numbered_list_item, to_do, toggle, code,
            image, divider, table, and many more.
        created_time (datetime): Date and time when the block was created (ISO 8601).
        last_edited_time (datetime): Date and time when the block was last edited
            (ISO 8601).
        created_by (PartialUser): A partial User object containing only the object
            type and ID. Used in created_by and last_edited_by fields.
        last_edited_by (PartialUser): A partial User object containing only the
            object type and ID. Used in created_by and last_edited_by fields.
        archived (bool): Whether the block has been archived.
        in_trash (bool): Whether the block is in the trash.
        has_children (bool): Whether the block has child blocks nested within it.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "object": "object",
        "id": "id",
        "mtype": "type",
        "created_time": "created_time",
        "last_edited_time": "last_edited_time",
        "has_children": "has_children",
        "parent": "parent",
        "created_by": "created_by",
        "last_edited_by": "last_edited_by",
        "archived": "archived",
        "in_trash": "in_trash",
    }

    _optionals = [
        "parent",
        "created_by",
        "last_edited_by",
        "archived",
        "in_trash",
    ]

    def __init__(
        self,
        object=None,
        id=None,
        mtype=None,
        created_time=None,
        last_edited_time=None,
        has_children=None,
        parent=APIHelper.SKIP,
        created_by=APIHelper.SKIP,
        last_edited_by=APIHelper.SKIP,
        archived=APIHelper.SKIP,
        in_trash=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Block instance."""
        # Initialize members of the class
        self.object = object
        self.id = id
        if parent is not APIHelper.SKIP:
            self.parent = parent
        self.mtype = mtype
        self.created_time =\
             APIHelper.apply_datetime_converter(
            created_time, APIHelper.RFC3339DateTime)\
             if created_time else None
        self.last_edited_time =\
             APIHelper.apply_datetime_converter(
            last_edited_time, APIHelper.RFC3339DateTime)\
             if last_edited_time else None
        if created_by is not APIHelper.SKIP:
            self.created_by = created_by
        if last_edited_by is not APIHelper.SKIP:
            self.last_edited_by = last_edited_by
        if archived is not APIHelper.SKIP:
            self.archived = archived
        if in_trash is not APIHelper.SKIP:
            self.in_trash = in_trash
        self.has_children = has_children

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        object =\
            dictionary.get("object")\
            if dictionary.get("object")\
                else None
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else None
        created_time = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_time")).datetime\
            if dictionary.get("created_time") else None
        last_edited_time = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("last_edited_time")).datetime\
            if dictionary.get("last_edited_time") else None
        has_children =\
            dictionary.get("has_children")\
            if "has_children" in dictionary.keys()\
                else None
        parent =\
            Parent.from_dictionary(
                dictionary.get("parent"))\
                if "parent" in dictionary.keys()\
                else APIHelper.SKIP
        created_by =\
            PartialUser.from_dictionary(
                dictionary.get("created_by"))\
                if "created_by" in dictionary.keys()\
                else APIHelper.SKIP
        last_edited_by =\
            PartialUser.from_dictionary(
                dictionary.get("last_edited_by"))\
                if "last_edited_by" in dictionary.keys()\
                else APIHelper.SKIP
        archived =\
            dictionary.get("archived")\
            if "archived" in dictionary.keys()\
                else APIHelper.SKIP
        in_trash =\
            dictionary.get("in_trash")\
            if "in_trash" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(object,
                   id,
                   mtype,
                   created_time,
                   last_edited_time,
                   has_children,
                   parent,
                   created_by,
                   last_edited_by,
                   archived,
                   in_trash,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.object,
                    type_callable=lambda value:
                        Object1.validate(value)) \
                and APIHelper.is_valid_type(
                    value=dictionary.id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.mtype,
                    type_callable=lambda value:
                        Type1.validate(value)) \
                and APIHelper.is_valid_type(
                    value=dictionary.created_time,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        APIHelper.RFC3339DateTime,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.last_edited_time,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        APIHelper.RFC3339DateTime,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.has_children,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        bool,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("object"),
                type_callable=lambda value:
                    Object1.validate(value)) \
            and APIHelper.is_valid_type(
                value=dictionary.get("id"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("type"),
                type_callable=lambda value:
                    Type1.validate(value)) \
            and APIHelper.is_valid_type(
                value=dictionary.get("created_time"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("last_edited_time"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("has_children"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    bool,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _object=self.object
        _id=self.id
        _parent=(
            self.parent
            if hasattr(self, "parent")
            else None
        )
        _mtype=self.mtype
        _created_time=self.created_time
        _last_edited_time=self.last_edited_time
        _created_by=(
            self.created_by
            if hasattr(self, "created_by")
            else None
        )
        _last_edited_by=(
            self.last_edited_by
            if hasattr(self, "last_edited_by")
            else None
        )
        _archived=(
            self.archived
            if hasattr(self, "archived")
            else None
        )
        _in_trash=(
            self.in_trash
            if hasattr(self, "in_trash")
            else None
        )
        _has_children=self.has_children
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"object={_object!r}, "
            f"id={_id!r}, "
            f"parent={_parent!r}, "
            f"mtype={_mtype!r}, "
            f"created_time={_created_time!r}, "
            f"last_edited_time={_last_edited_time!r}, "
            f"created_by={_created_by!r}, "
            f"last_edited_by={_last_edited_by!r}, "
            f"archived={_archived!r}, "
            f"in_trash={_in_trash!r}, "
            f"has_children={_has_children!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _object=self.object
        _id=self.id
        _parent=(
            self.parent
            if hasattr(self, "parent")
            else None
        )
        _mtype=self.mtype
        _created_time=self.created_time
        _last_edited_time=self.last_edited_time
        _created_by=(
            self.created_by
            if hasattr(self, "created_by")
            else None
        )
        _last_edited_by=(
            self.last_edited_by
            if hasattr(self, "last_edited_by")
            else None
        )
        _archived=(
            self.archived
            if hasattr(self, "archived")
            else None
        )
        _in_trash=(
            self.in_trash
            if hasattr(self, "in_trash")
            else None
        )
        _has_children=self.has_children
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"object={_object!s}, "
            f"id={_id!s}, "
            f"parent={_parent!s}, "
            f"mtype={_mtype!s}, "
            f"created_time={_created_time!s}, "
            f"last_edited_time={_last_edited_time!s}, "
            f"created_by={_created_by!s}, "
            f"last_edited_by={_last_edited_by!s}, "
            f"archived={_archived!s}, "
            f"in_trash={_in_trash!s}, "
            f"has_children={_has_children!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
