"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper
from notion.models.block import Block


class BlocksChildrenRequest(object):
    """Implementation of the 'Blocks Children Request' model.

    Attributes:
        children (List[Block]): Array of block objects to append as children. Maximum
            100 blocks per request.
        after (uuid|str): The ID of an existing block to insert the new children
            after. If omitted, blocks are appended to the end.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "children": "children",
        "after": "after",
    }

    _optionals = [
        "after",
    ]

    def __init__(
        self,
        children=None,
        after=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a BlocksChildrenRequest instance."""
        # Initialize members of the class
        self.children = children
        if after is not APIHelper.SKIP:
            self.after = after

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        children = None
        if dictionary.get("children") is not None:
            children = [
                Block.from_dictionary(x)
                    for x in dictionary.get("children")
            ]
        after =\
            dictionary.get("after")\
            if dictionary.get("after")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(children,
                   after,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _children=self.children
        _after=(
            self.after
            if hasattr(self, "after")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"children={_children!r}, "
            f"after={_after!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _children=self.children
        _after=(
            self.after
            if hasattr(self, "after")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"children={_children!s}, "
            f"after={_after!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
