"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper
from notion.models.owner import Owner


class Bot(object):
    """Implementation of the 'Bot' model.

    Bot-specific information. Only present when type is "bot".

    Attributes:
        owner (Owner): Information about the bot's owner.
        workspace_name (str): The name of the workspace the bot belongs to.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "owner": "owner",
        "workspace_name": "workspace_name",
    }

    _optionals = [
        "owner",
        "workspace_name",
    ]

    _nullables = [
        "workspace_name",
    ]

    def __init__(
        self,
        owner=APIHelper.SKIP,
        workspace_name=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Bot instance."""
        # Initialize members of the class
        if owner is not APIHelper.SKIP:
            self.owner = owner
        if workspace_name is not APIHelper.SKIP:
            self.workspace_name = workspace_name

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        owner =\
            Owner.from_dictionary(
                dictionary.get("owner"))\
                if "owner" in dictionary.keys()\
                else APIHelper.SKIP
        workspace_name =\
            dictionary.get("workspace_name")\
            if "workspace_name" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(owner,
                   workspace_name,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _owner=(
            self.owner
            if hasattr(self, "owner")
            else None
        )
        _workspace_name=(
            self.workspace_name
            if hasattr(self, "workspace_name")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"owner={_owner!r}, "
            f"workspace_name={_workspace_name!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _owner=(
            self.owner
            if hasattr(self, "owner")
            else None
        )
        _workspace_name=(
            self.workspace_name
            if hasattr(self, "workspace_name")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"owner={_owner!s}, "
            f"workspace_name={_workspace_name!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
