"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper
from notion.models.parent_1 import Parent1
from notion.models.partial_user import PartialUser
from notion.models.rich_text import RichText


class Comment(object):
    """Implementation of the 'Comment' model.

    A Comment object represents a comment on a Notion page or block. Comments contain
    rich text content and are associated with discussion threads.

    Attributes:
        object (Object11): Always "comment" for comment objects.
        id (uuid|str): Unique identifier for the comment.
        parent (Parent1): The parent page or block the comment belongs to.
        discussion_id (uuid|str): The ID of the discussion thread the comment belongs
            to.
        created_time (datetime): Date and time when the comment was created (ISO
            8601).
        last_edited_time (datetime): Date and time when the comment was last edited
            (ISO 8601).
        created_by (PartialUser): A partial User object containing only the object
            type and ID. Used in created_by and last_edited_by fields.
        rich_text (List[RichText]): Rich text content of the comment.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "object": "object",
        "id": "id",
        "parent": "parent",
        "discussion_id": "discussion_id",
        "created_time": "created_time",
        "last_edited_time": "last_edited_time",
        "created_by": "created_by",
        "rich_text": "rich_text",
    }

    def __init__(
        self,
        object=None,
        id=None,
        parent=None,
        discussion_id=None,
        created_time=None,
        last_edited_time=None,
        created_by=None,
        rich_text=None,
        additional_properties=None):
        """Initialize a Comment instance."""
        # Initialize members of the class
        self.object = object
        self.id = id
        self.parent = parent
        self.discussion_id = discussion_id
        self.created_time =\
             APIHelper.apply_datetime_converter(
            created_time, APIHelper.RFC3339DateTime)\
             if created_time else None
        self.last_edited_time =\
             APIHelper.apply_datetime_converter(
            last_edited_time, APIHelper.RFC3339DateTime)\
             if last_edited_time else None
        self.created_by = created_by
        self.rich_text = rich_text

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        object =\
            dictionary.get("object")\
            if dictionary.get("object")\
                else None
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        parent =\
            Parent1.from_dictionary(
                dictionary.get("parent"))\
                if dictionary.get("parent") else None
        discussion_id =\
            dictionary.get("discussion_id")\
            if dictionary.get("discussion_id")\
                else None
        created_time = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_time")).datetime\
            if dictionary.get("created_time") else None
        last_edited_time = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("last_edited_time")).datetime\
            if dictionary.get("last_edited_time") else None
        created_by =\
            PartialUser.from_dictionary(
                dictionary.get("created_by"))\
                if dictionary.get("created_by") else None
        rich_text = None
        if dictionary.get("rich_text") is not None:
            rich_text = [
                RichText.from_dictionary(x)
                    for x in dictionary.get("rich_text")
            ]

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(object,
                   id,
                   parent,
                   discussion_id,
                   created_time,
                   last_edited_time,
                   created_by,
                   rich_text,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _object=self.object
        _id=self.id
        _parent=self.parent
        _discussion_id=self.discussion_id
        _created_time=self.created_time
        _last_edited_time=self.last_edited_time
        _created_by=self.created_by
        _rich_text=self.rich_text
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"object={_object!r}, "
            f"id={_id!r}, "
            f"parent={_parent!r}, "
            f"discussion_id={_discussion_id!r}, "
            f"created_time={_created_time!r}, "
            f"last_edited_time={_last_edited_time!r}, "
            f"created_by={_created_by!r}, "
            f"rich_text={_rich_text!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _object=self.object
        _id=self.id
        _parent=self.parent
        _discussion_id=self.discussion_id
        _created_time=self.created_time
        _last_edited_time=self.last_edited_time
        _created_by=self.created_by
        _rich_text=self.rich_text
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"object={_object!s}, "
            f"id={_id!s}, "
            f"parent={_parent!s}, "
            f"discussion_id={_discussion_id!s}, "
            f"created_time={_created_time!s}, "
            f"last_edited_time={_last_edited_time!s}, "
            f"created_by={_created_by!s}, "
            f"rich_text={_rich_text!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
