"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper
from notion.models.parent_11 import Parent11
from notion.models.rich_text import RichText


class CommentsRequest(object):
    """Implementation of the 'Comments Request' model.

    Attributes:
        parent (Parent11): The parent page to create the comment on. Required if
            discussion_id is not provided.
        discussion_id (uuid|str): The ID of an existing discussion thread to add the
            comment to. Required if parent is not provided.
        rich_text (List[RichText]): Rich text content of the comment.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "rich_text": "rich_text",
        "parent": "parent",
        "discussion_id": "discussion_id",
    }

    _optionals = [
        "parent",
        "discussion_id",
    ]

    def __init__(
        self,
        rich_text=None,
        parent=APIHelper.SKIP,
        discussion_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CommentsRequest instance."""
        # Initialize members of the class
        if parent is not APIHelper.SKIP:
            self.parent = parent
        if discussion_id is not APIHelper.SKIP:
            self.discussion_id = discussion_id
        self.rich_text = rich_text

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        rich_text = None
        if dictionary.get("rich_text") is not None:
            rich_text = [
                RichText.from_dictionary(x)
                    for x in dictionary.get("rich_text")
            ]
        parent =\
            Parent11.from_dictionary(
                dictionary.get("parent"))\
                if "parent" in dictionary.keys()\
                else APIHelper.SKIP
        discussion_id =\
            dictionary.get("discussion_id")\
            if dictionary.get("discussion_id")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(rich_text,
                   parent,
                   discussion_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _parent=(
            self.parent
            if hasattr(self, "parent")
            else None
        )
        _discussion_id=(
            self.discussion_id
            if hasattr(self, "discussion_id")
            else None
        )
        _rich_text=self.rich_text
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"parent={_parent!r}, "
            f"discussion_id={_discussion_id!r}, "
            f"rich_text={_rich_text!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _parent=(
            self.parent
            if hasattr(self, "parent")
            else None
        )
        _discussion_id=(
            self.discussion_id
            if hasattr(self, "discussion_id")
            else None
        )
        _rich_text=self.rich_text
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"parent={_parent!s}, "
            f"discussion_id={_discussion_id!s}, "
            f"rich_text={_rich_text!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
