"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper
from notion.models.external_file_1 import ExternalFile1
from notion.models.parent import Parent
from notion.models.property_schema import PropertySchema
from notion.models.rich_text import RichText


class DatabasesRequest(object):
    """Implementation of the 'Databases Request' model.

    Attributes:
        parent (Parent): A Parent object represents the parent of a page, database,
            or block. The parent can be a workspace, page, database, or block.
        title (List[RichText]): Rich text array for the database title.
        description (List[RichText]): Rich text array for the database description.
        properties (Dict[str, PropertySchema]): Schema of the database properties.
            Keys are property names, values are property schema objects defining the
            type and configuration.
        is_inline (bool): Whether the database appears inline within its parent page
            rather than as a full page.
        icon (Emoji | ExternalFile | None): Database icon.
        cover (ExternalFile1): Database cover image.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "parent": "parent",
        "properties": "properties",
        "title": "title",
        "description": "description",
        "is_inline": "is_inline",
        "icon": "icon",
        "cover": "cover",
    }

    _optionals = [
        "title",
        "description",
        "is_inline",
        "icon",
        "cover",
    ]

    def __init__(
        self,
        parent=None,
        properties=None,
        title=APIHelper.SKIP,
        description=APIHelper.SKIP,
        is_inline=APIHelper.SKIP,
        icon=APIHelper.SKIP,
        cover=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a DatabasesRequest instance."""
        # Initialize members of the class
        self.parent = parent
        if title is not APIHelper.SKIP:
            self.title = title
        if description is not APIHelper.SKIP:
            self.description = description
        self.properties = properties
        if is_inline is not APIHelper.SKIP:
            self.is_inline = is_inline
        if icon is not APIHelper.SKIP:
            self.icon = icon
        if cover is not APIHelper.SKIP:
            self.cover = cover

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from notion.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        parent =\
            Parent.from_dictionary(
                dictionary.get("parent"))\
                if dictionary.get("parent") else None
        properties =\
            PropertySchema.from_dictionary(
                dictionary.get("properties"))\
                if dictionary.get("properties") else None
        title = None
        if dictionary.get("title") is not None:
            title = [
                RichText.from_dictionary(x)
                    for x in dictionary.get("title")
            ]
        else:
            title = APIHelper.SKIP
        description = None
        if dictionary.get("description") is not None:
            description = [
                RichText.from_dictionary(x)
                    for x in dictionary.get("description")
            ]
        else:
            description = APIHelper.SKIP
        is_inline =\
            dictionary.get("is_inline")\
            if "is_inline" in dictionary.keys()\
                else APIHelper.SKIP
        icon = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("DatabasesRequestIcon"),
            dictionary.get("icon"),
            False)\
            if dictionary.get("icon") is not None\
            else APIHelper.SKIP
        cover =\
            ExternalFile1.from_dictionary(
                dictionary.get("cover"))\
                if "cover" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(parent,
                   properties,
                   title,
                   description,
                   is_inline,
                   icon,
                   cover,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _parent=self.parent
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _properties=self.properties
        _is_inline=(
            self.is_inline
            if hasattr(self, "is_inline")
            else None
        )
        _icon=(
            self.icon
            if hasattr(self, "icon")
            else None
        )
        _cover=(
            self.cover
            if hasattr(self, "cover")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"parent={_parent!r}, "
            f"title={_title!r}, "
            f"description={_description!r}, "
            f"properties={_properties!r}, "
            f"is_inline={_is_inline!r}, "
            f"icon={_icon!r}, "
            f"cover={_cover!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _parent=self.parent
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _properties=self.properties
        _is_inline=(
            self.is_inline
            if hasattr(self, "is_inline")
            else None
        )
        _icon=(
            self.icon
            if hasattr(self, "icon")
            else None
        )
        _cover=(
            self.cover
            if hasattr(self, "cover")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"parent={_parent!s}, "
            f"title={_title!s}, "
            f"description={_description!s}, "
            f"properties={_properties!s}, "
            f"is_inline={_is_inline!s}, "
            f"icon={_icon!s}, "
            f"cover={_cover!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
