"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper
from notion.models.file import File
from notion.models.parent import Parent
from notion.models.partial_user import PartialUser
from notion.models.property_schema import PropertySchema
from notion.models.rich_text import RichText


class Database(object):
    """Implementation of the 'Database' model.

    A Database object represents a database in Notion. Databases are collections of
    pages that share a common schema of properties. The schema defines the columns
    and their types that all pages in the database will have.

    Attributes:
        object (Object12): Always "database" for database objects.
        id (uuid|str): Unique identifier for the database.
        created_time (datetime): Date and time when the database was created (ISO
            8601).
        last_edited_time (datetime): Date and time when the database was last edited
            (ISO 8601).
        created_by (PartialUser): A partial User object containing only the object
            type and ID. Used in created_by and last_edited_by fields.
        last_edited_by (PartialUser): A partial User object containing only the
            object type and ID. Used in created_by and last_edited_by fields.
        title (List[RichText]): Title of the database as rich text.
        description (List[RichText]): Description of the database as rich text.
        icon (Emoji | File | None): Database icon, either an emoji or file.
        cover (File): Database cover image.
        properties (Dict[str, PropertySchema]): Schema of database properties. Keys
            are property names, values are property schema objects defining the type
            and configuration of each column.
        parent (Parent): A Parent object represents the parent of a page, database,
            or block. The parent can be a workspace, page, database, or block.
        url (str): The URL of the database in Notion.
        public_url (str): The public URL of the database, if published to the web.
            Otherwise null.
        archived (bool): Whether the database has been archived.
        in_trash (bool): Whether the database is in the trash.
        is_inline (bool): Whether the database is inline (appears within its parent
            page rather than as a full page).
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "object": "object",
        "id": "id",
        "created_time": "created_time",
        "last_edited_time": "last_edited_time",
        "created_by": "created_by",
        "last_edited_by": "last_edited_by",
        "title": "title",
        "description": "description",
        "properties": "properties",
        "parent": "parent",
        "url": "url",
        "archived": "archived",
        "icon": "icon",
        "cover": "cover",
        "public_url": "public_url",
        "in_trash": "in_trash",
        "is_inline": "is_inline",
    }

    _optionals = [
        "icon",
        "cover",
        "public_url",
        "in_trash",
        "is_inline",
    ]

    _nullables = [
        "icon",
        "cover",
        "public_url",
    ]

    def __init__(
        self,
        object=None,
        id=None,
        created_time=None,
        last_edited_time=None,
        created_by=None,
        last_edited_by=None,
        title=None,
        description=None,
        properties=None,
        parent=None,
        url=None,
        archived=None,
        icon=APIHelper.SKIP,
        cover=APIHelper.SKIP,
        public_url=APIHelper.SKIP,
        in_trash=APIHelper.SKIP,
        is_inline=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Database instance."""
        # Initialize members of the class
        self.object = object
        self.id = id
        self.created_time =\
             APIHelper.apply_datetime_converter(
            created_time, APIHelper.RFC3339DateTime)\
             if created_time else None
        self.last_edited_time =\
             APIHelper.apply_datetime_converter(
            last_edited_time, APIHelper.RFC3339DateTime)\
             if last_edited_time else None
        self.created_by = created_by
        self.last_edited_by = last_edited_by
        self.title = title
        self.description = description
        if icon is not APIHelper.SKIP:
            self.icon = icon
        if cover is not APIHelper.SKIP:
            self.cover = cover
        self.properties = properties
        self.parent = parent
        self.url = url
        if public_url is not APIHelper.SKIP:
            self.public_url = public_url
        self.archived = archived
        if in_trash is not APIHelper.SKIP:
            self.in_trash = in_trash
        if is_inline is not APIHelper.SKIP:
            self.is_inline = is_inline

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from notion.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        object =\
            dictionary.get("object")\
            if dictionary.get("object")\
                else None
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        created_time = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_time")).datetime\
            if dictionary.get("created_time") else None
        last_edited_time = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("last_edited_time")).datetime\
            if dictionary.get("last_edited_time") else None
        created_by =\
            PartialUser.from_dictionary(
                dictionary.get("created_by"))\
                if dictionary.get("created_by") else None
        last_edited_by =\
            PartialUser.from_dictionary(
                dictionary.get("last_edited_by"))\
                if dictionary.get("last_edited_by") else None
        title = None
        if dictionary.get("title") is not None:
            title = [
                RichText.from_dictionary(x)
                    for x in dictionary.get("title")
            ]
        description = None
        if dictionary.get("description") is not None:
            description = [
                RichText.from_dictionary(x)
                    for x in dictionary.get("description")
            ]
        properties =\
            PropertySchema.from_dictionary(
                dictionary.get("properties"))\
                if dictionary.get("properties") else None
        parent =\
            Parent.from_dictionary(
                dictionary.get("parent"))\
                if dictionary.get("parent") else None
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else None
        archived =\
            dictionary.get("archived")\
            if "archived" in dictionary.keys()\
                else None
        if "icon" in dictionary.keys():
            icon = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("DatabaseIcon"),
            dictionary.get("icon"),
            False)\
            if dictionary.get("icon") is not None\
            else None
        else:
            icon = APIHelper.SKIP
        if "cover" in dictionary.keys():
            cover =\
                File.from_dictionary(
                dictionary.get("cover"))\
                if dictionary.get("cover") else None
        else:
            cover = APIHelper.SKIP
        public_url =\
            dictionary.get("public_url")\
            if "public_url" in dictionary.keys()\
                else APIHelper.SKIP
        in_trash =\
            dictionary.get("in_trash")\
            if "in_trash" in dictionary.keys()\
                else APIHelper.SKIP
        is_inline =\
            dictionary.get("is_inline")\
            if "is_inline" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(object,
                   id,
                   created_time,
                   last_edited_time,
                   created_by,
                   last_edited_by,
                   title,
                   description,
                   properties,
                   parent,
                   url,
                   archived,
                   icon,
                   cover,
                   public_url,
                   in_trash,
                   is_inline,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _object=self.object
        _id=self.id
        _created_time=self.created_time
        _last_edited_time=self.last_edited_time
        _created_by=self.created_by
        _last_edited_by=self.last_edited_by
        _title=self.title
        _description=self.description
        _icon=(
            self.icon
            if hasattr(self, "icon")
            else None
        )
        _cover=(
            self.cover
            if hasattr(self, "cover")
            else None
        )
        _properties=self.properties
        _parent=self.parent
        _url=self.url
        _public_url=(
            self.public_url
            if hasattr(self, "public_url")
            else None
        )
        _archived=self.archived
        _in_trash=(
            self.in_trash
            if hasattr(self, "in_trash")
            else None
        )
        _is_inline=(
            self.is_inline
            if hasattr(self, "is_inline")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"object={_object!r}, "
            f"id={_id!r}, "
            f"created_time={_created_time!r}, "
            f"last_edited_time={_last_edited_time!r}, "
            f"created_by={_created_by!r}, "
            f"last_edited_by={_last_edited_by!r}, "
            f"title={_title!r}, "
            f"description={_description!r}, "
            f"icon={_icon!r}, "
            f"cover={_cover!r}, "
            f"properties={_properties!r}, "
            f"parent={_parent!r}, "
            f"url={_url!r}, "
            f"public_url={_public_url!r}, "
            f"archived={_archived!r}, "
            f"in_trash={_in_trash!r}, "
            f"is_inline={_is_inline!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _object=self.object
        _id=self.id
        _created_time=self.created_time
        _last_edited_time=self.last_edited_time
        _created_by=self.created_by
        _last_edited_by=self.last_edited_by
        _title=self.title
        _description=self.description
        _icon=(
            self.icon
            if hasattr(self, "icon")
            else None
        )
        _cover=(
            self.cover
            if hasattr(self, "cover")
            else None
        )
        _properties=self.properties
        _parent=self.parent
        _url=self.url
        _public_url=(
            self.public_url
            if hasattr(self, "public_url")
            else None
        )
        _archived=self.archived
        _in_trash=(
            self.in_trash
            if hasattr(self, "in_trash")
            else None
        )
        _is_inline=(
            self.is_inline
            if hasattr(self, "is_inline")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"object={_object!s}, "
            f"id={_id!s}, "
            f"created_time={_created_time!s}, "
            f"last_edited_time={_last_edited_time!s}, "
            f"created_by={_created_by!s}, "
            f"last_edited_by={_last_edited_by!s}, "
            f"title={_title!s}, "
            f"description={_description!s}, "
            f"icon={_icon!s}, "
            f"cover={_cover!s}, "
            f"properties={_properties!s}, "
            f"parent={_parent!s}, "
            f"url={_url!s}, "
            f"public_url={_public_url!s}, "
            f"archived={_archived!s}, "
            f"in_trash={_in_trash!s}, "
            f"is_inline={_is_inline!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
