"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper
from notion.models.sort import Sort


class DatabasesQueryRequest(object):
    """Implementation of the 'Databases Query Request' model.

    Attributes:
        filter (Any): Filter conditions to apply. Supports compound filters using
            and/or as well as property-specific filters.
        sorts (List[Sort]): Sort conditions to order the results. Multiple sorts can
            be applied; they are processed in the order provided.
        start_cursor (str): Pagination cursor from a previous response to continue
            fetching results.
        page_size (int): Maximum number of results to return (max 100).
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "filter": "filter",
        "sorts": "sorts",
        "start_cursor": "start_cursor",
        "page_size": "page_size",
    }

    _optionals = [
        "filter",
        "sorts",
        "start_cursor",
        "page_size",
    ]

    def __init__(
        self,
        filter=APIHelper.SKIP,
        sorts=APIHelper.SKIP,
        start_cursor=APIHelper.SKIP,
        page_size=100,
        additional_properties=None):
        """Initialize a DatabasesQueryRequest instance."""
        # Initialize members of the class
        if filter is not APIHelper.SKIP:
            self.filter = filter
        if sorts is not APIHelper.SKIP:
            self.sorts = sorts
        if start_cursor is not APIHelper.SKIP:
            self.start_cursor = start_cursor
        self.page_size = page_size

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        filter =\
            dictionary.get("filter")\
            if dictionary.get("filter")\
                else APIHelper.SKIP
        sorts = None
        if dictionary.get("sorts") is not None:
            sorts = [
                Sort.from_dictionary(x)
                    for x in dictionary.get("sorts")
            ]
        else:
            sorts = APIHelper.SKIP
        start_cursor =\
            dictionary.get("start_cursor")\
            if dictionary.get("start_cursor")\
                else APIHelper.SKIP
        page_size =\
            dictionary.get("page_size")\
            if dictionary.get("page_size")\
                else 100

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(filter,
                   sorts,
                   start_cursor,
                   page_size,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _filter=(
            self.filter
            if hasattr(self, "filter")
            else None
        )
        _sorts=(
            self.sorts
            if hasattr(self, "sorts")
            else None
        )
        _start_cursor=(
            self.start_cursor
            if hasattr(self, "start_cursor")
            else None
        )
        _page_size=(
            self.page_size
            if hasattr(self, "page_size")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"filter={_filter!r}, "
            f"sorts={_sorts!r}, "
            f"start_cursor={_start_cursor!r}, "
            f"page_size={_page_size!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _filter=(
            self.filter
            if hasattr(self, "filter")
            else None
        )
        _sorts=(
            self.sorts
            if hasattr(self, "sorts")
            else None
        )
        _start_cursor=(
            self.start_cursor
            if hasattr(self, "start_cursor")
            else None
        )
        _page_size=(
            self.page_size
            if hasattr(self, "page_size")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"filter={_filter!s}, "
            f"sorts={_sorts!s}, "
            f"start_cursor={_start_cursor!s}, "
            f"page_size={_page_size!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
