"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper
from notion.models.external_file import ExternalFile
from notion.models.rich_text import RichText


class DatabasesRequest1(object):
    """Implementation of the 'Databases Request1' model.

    Attributes:
        title (List[RichText]): Updated database title as rich text.
        description (List[RichText]): Updated database description as rich text.
        properties (Any): Updated property schema. Include only properties to add or
            modify. Set a property value to null to remove it.
        icon (Emoji | ExternalFile | None): Updated database icon.
        cover (ExternalFile): Updated database cover image.
        is_inline (bool): Whether the database is inline.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "title": "title",
        "description": "description",
        "properties": "properties",
        "icon": "icon",
        "cover": "cover",
        "is_inline": "is_inline",
    }

    _optionals = [
        "title",
        "description",
        "properties",
        "icon",
        "cover",
        "is_inline",
    ]

    _nullables = [
        "icon",
        "cover",
    ]

    def __init__(
        self,
        title=APIHelper.SKIP,
        description=APIHelper.SKIP,
        properties=APIHelper.SKIP,
        icon=APIHelper.SKIP,
        cover=APIHelper.SKIP,
        is_inline=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a DatabasesRequest1 instance."""
        # Initialize members of the class
        if title is not APIHelper.SKIP:
            self.title = title
        if description is not APIHelper.SKIP:
            self.description = description
        if properties is not APIHelper.SKIP:
            self.properties = properties
        if icon is not APIHelper.SKIP:
            self.icon = icon
        if cover is not APIHelper.SKIP:
            self.cover = cover
        if is_inline is not APIHelper.SKIP:
            self.is_inline = is_inline

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from notion.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        title = None
        if dictionary.get("title") is not None:
            title = [
                RichText.from_dictionary(x)
                    for x in dictionary.get("title")
            ]
        else:
            title = APIHelper.SKIP
        description = None
        if dictionary.get("description") is not None:
            description = [
                RichText.from_dictionary(x)
                    for x in dictionary.get("description")
            ]
        else:
            description = APIHelper.SKIP
        properties =\
            dictionary.get("properties")\
            if dictionary.get("properties")\
                else APIHelper.SKIP
        if "icon" in dictionary.keys():
            icon = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("DatabasesRequest1Icon"),
            dictionary.get("icon"),
            False)\
            if dictionary.get("icon") is not None\
            else None
        else:
            icon = APIHelper.SKIP
        if "cover" in dictionary.keys():
            cover =\
                ExternalFile.from_dictionary(
                dictionary.get("cover"))\
                if dictionary.get("cover") else None
        else:
            cover = APIHelper.SKIP
        is_inline =\
            dictionary.get("is_inline")\
            if "is_inline" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(title,
                   description,
                   properties,
                   icon,
                   cover,
                   is_inline,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _properties=(
            self.properties
            if hasattr(self, "properties")
            else None
        )
        _icon=(
            self.icon
            if hasattr(self, "icon")
            else None
        )
        _cover=(
            self.cover
            if hasattr(self, "cover")
            else None
        )
        _is_inline=(
            self.is_inline
            if hasattr(self, "is_inline")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"title={_title!r}, "
            f"description={_description!r}, "
            f"properties={_properties!r}, "
            f"icon={_icon!r}, "
            f"cover={_cover!r}, "
            f"is_inline={_is_inline!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _properties=(
            self.properties
            if hasattr(self, "properties")
            else None
        )
        _icon=(
            self.icon
            if hasattr(self, "icon")
            else None
        )
        _cover=(
            self.cover
            if hasattr(self, "cover")
            else None
        )
        _is_inline=(
            self.is_inline
            if hasattr(self, "is_inline")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"title={_title!s}, "
            f"description={_description!s}, "
            f"properties={_properties!s}, "
            f"icon={_icon!s}, "
            f"cover={_cover!s}, "
            f"is_inline={_is_inline!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
