"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper
from notion.models.file_1 import File1
from notion.models.link import Link
from notion.models.rich_text import RichText
from notion.models.type_21 import Type21


class File(object):
    """Implementation of the 'File' model.

    A File object represents a file in Notion. Files can be either hosted by Notion
    (type "file") or externally hosted (type "external").

    Attributes:
        mtype (Type21): The type of file hosting.
        file (File1): Notion-hosted file details. Present when type is "file". These
            URLs expire after one hour.
        external (Link): External file details. Present when type is "external".
        name (str): The name of the file.
        caption (List[RichText]): Caption for the file as rich text.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": "type",
        "file": "file",
        "external": "external",
        "name": "name",
        "caption": "caption",
    }

    _optionals = [
        "file",
        "external",
        "name",
        "caption",
    ]

    def __init__(
        self,
        mtype=None,
        file=APIHelper.SKIP,
        external=APIHelper.SKIP,
        name=APIHelper.SKIP,
        caption=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a File instance."""
        # Initialize members of the class
        self.mtype = mtype
        if file is not APIHelper.SKIP:
            self.file = file
        if external is not APIHelper.SKIP:
            self.external = external
        if name is not APIHelper.SKIP:
            self.name = name
        if caption is not APIHelper.SKIP:
            self.caption = caption

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else None
        file =\
            File1.from_dictionary(
                dictionary.get("file"))\
                if "file" in dictionary.keys()\
                else APIHelper.SKIP
        external =\
            Link.from_dictionary(
                dictionary.get("external"))\
                if "external" in dictionary.keys()\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        caption = None
        if dictionary.get("caption") is not None:
            caption = [
                RichText.from_dictionary(x)
                    for x in dictionary.get("caption")
            ]
        else:
            caption = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(mtype,
                   file,
                   external,
                   name,
                   caption,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.mtype,
                    type_callable=lambda value:
                        Type21.validate(value))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("type"),
                type_callable=lambda value:
                    Type21.validate(value))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mtype=self.mtype
        _file=(
            self.file
            if hasattr(self, "file")
            else None
        )
        _external=(
            self.external
            if hasattr(self, "external")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _caption=(
            self.caption
            if hasattr(self, "caption")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!r}, "
            f"file={_file!r}, "
            f"external={_external!r}, "
            f"name={_name!r}, "
            f"caption={_caption!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mtype=self.mtype
        _file=(
            self.file
            if hasattr(self, "file")
            else None
        )
        _external=(
            self.external
            if hasattr(self, "external")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _caption=(
            self.caption
            if hasattr(self, "caption")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!s}, "
            f"file={_file!s}, "
            f"external={_external!s}, "
            f"name={_name!s}, "
            f"caption={_caption!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
