"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper


class File1(object):
    """Implementation of the 'File1' model.

    Notion-hosted file details. Present when type is "file". These URLs expire after
    one hour.

    Attributes:
        url (str): The authenticated S3 URL for the file.
        expiry_time (datetime): The expiration time of the URL.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "url": "url",
        "expiry_time": "expiry_time",
    }

    _optionals = [
        "url",
        "expiry_time",
    ]

    def __init__(
        self,
        url=APIHelper.SKIP,
        expiry_time=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a File1 instance."""
        # Initialize members of the class
        if url is not APIHelper.SKIP:
            self.url = url
        if expiry_time is not APIHelper.SKIP:
            self.expiry_time =\
                 APIHelper.apply_datetime_converter(
                expiry_time, APIHelper.RFC3339DateTime)\
                 if expiry_time else None

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else APIHelper.SKIP
        expiry_time = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("expiry_time")).datetime\
            if dictionary.get("expiry_time") else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(url,
                   expiry_time,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _expiry_time=(
            self.expiry_time
            if hasattr(self, "expiry_time")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"url={_url!r}, "
            f"expiry_time={_expiry_time!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _expiry_time=(
            self.expiry_time
            if hasattr(self, "expiry_time")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"url={_url!s}, "
            f"expiry_time={_expiry_time!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
