"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper


class Filter(object):
    """Implementation of the 'Filter' model.

    Filter conditions. Currently only supports filtering by object type (page or
    database).

    Attributes:
        value (Value): The type of object to filter by.
        property (Property): Must be "object".
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "value": "value",
        "property": "property",
    }

    _optionals = [
        "value",
        "property",
    ]

    def __init__(
        self,
        value=APIHelper.SKIP,
        property=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Filter instance."""
        # Initialize members of the class
        if value is not APIHelper.SKIP:
            self.value = value
        if property is not APIHelper.SKIP:
            self.property = property

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        value =\
            dictionary.get("value")\
            if dictionary.get("value")\
                else APIHelper.SKIP
        property =\
            dictionary.get("property")\
            if dictionary.get("property")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(value,
                   property,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _value=(
            self.value
            if hasattr(self, "value")
            else None
        )
        _property=(
            self.property
            if hasattr(self, "property")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"value={_value!r}, "
            f"property={_property!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _value=(
            self.value
            if hasattr(self, "value")
            else None
        )
        _property=(
            self.property
            if hasattr(self, "property")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"value={_value!s}, "
            f"property={_property!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
