"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper
from notion.models.file import File
from notion.models.parent import Parent
from notion.models.partial_user import PartialUser


class Page(object):
    """Implementation of the 'Page' model.

    A Page object represents a page in a Notion workspace. Pages can exist as
    standalone pages in a workspace or as items within a database. Each page has
    properties, which are metadata fields defined by its parent database schema or by
    the page itself.

    Attributes:
        object (Object21): Always "page" for page objects.
        id (uuid|str): Unique identifier for the page.
        created_time (datetime): Date and time when the page was created (ISO 8601).
        last_edited_time (datetime): Date and time when the page was last edited (ISO
            8601).
        created_by (PartialUser): A partial User object containing only the object
            type and ID. Used in created_by and last_edited_by fields.
        last_edited_by (PartialUser): A partial User object containing only the
            object type and ID. Used in created_by and last_edited_by fields.
        archived (bool): Whether the page has been archived (trashed).
        in_trash (bool): Whether the page is in the trash.
        icon (Emoji | File | None): Page icon, either an emoji or file.
        cover (File): Page cover image.
        properties (Any): Property values of the page. Keys are property names or IDs.
        parent (Parent): A Parent object represents the parent of a page, database,
            or block. The parent can be a workspace, page, database, or block.
        url (str): The URL of the page in Notion.
        public_url (str): The public URL of the page, if the page has been published
            to the web. Otherwise null.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "object": "object",
        "id": "id",
        "created_time": "created_time",
        "last_edited_time": "last_edited_time",
        "created_by": "created_by",
        "last_edited_by": "last_edited_by",
        "archived": "archived",
        "properties": "properties",
        "parent": "parent",
        "url": "url",
        "in_trash": "in_trash",
        "icon": "icon",
        "cover": "cover",
        "public_url": "public_url",
    }

    _optionals = [
        "in_trash",
        "icon",
        "cover",
        "public_url",
    ]

    _nullables = [
        "icon",
        "cover",
        "public_url",
    ]

    def __init__(
        self,
        object=None,
        id=None,
        created_time=None,
        last_edited_time=None,
        created_by=None,
        last_edited_by=None,
        archived=None,
        properties=None,
        parent=None,
        url=None,
        in_trash=APIHelper.SKIP,
        icon=APIHelper.SKIP,
        cover=APIHelper.SKIP,
        public_url=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Page instance."""
        # Initialize members of the class
        self.object = object
        self.id = id
        self.created_time =\
             APIHelper.apply_datetime_converter(
            created_time, APIHelper.RFC3339DateTime)\
             if created_time else None
        self.last_edited_time =\
             APIHelper.apply_datetime_converter(
            last_edited_time, APIHelper.RFC3339DateTime)\
             if last_edited_time else None
        self.created_by = created_by
        self.last_edited_by = last_edited_by
        self.archived = archived
        if in_trash is not APIHelper.SKIP:
            self.in_trash = in_trash
        if icon is not APIHelper.SKIP:
            self.icon = icon
        if cover is not APIHelper.SKIP:
            self.cover = cover
        self.properties = properties
        self.parent = parent
        self.url = url
        if public_url is not APIHelper.SKIP:
            self.public_url = public_url

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from notion.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        object =\
            dictionary.get("object")\
            if dictionary.get("object")\
                else None
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        created_time = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_time")).datetime\
            if dictionary.get("created_time") else None
        last_edited_time = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("last_edited_time")).datetime\
            if dictionary.get("last_edited_time") else None
        created_by =\
            PartialUser.from_dictionary(
                dictionary.get("created_by"))\
                if dictionary.get("created_by") else None
        last_edited_by =\
            PartialUser.from_dictionary(
                dictionary.get("last_edited_by"))\
                if dictionary.get("last_edited_by") else None
        archived =\
            dictionary.get("archived")\
            if "archived" in dictionary.keys()\
                else None
        properties =\
            dictionary.get("properties")\
            if dictionary.get("properties")\
                else None
        parent =\
            Parent.from_dictionary(
                dictionary.get("parent"))\
                if dictionary.get("parent") else None
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else None
        in_trash =\
            dictionary.get("in_trash")\
            if "in_trash" in dictionary.keys()\
                else APIHelper.SKIP
        if "icon" in dictionary.keys():
            icon = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("PageIcon"),
            dictionary.get("icon"),
            False)\
            if dictionary.get("icon") is not None\
            else None
        else:
            icon = APIHelper.SKIP
        if "cover" in dictionary.keys():
            cover =\
                File.from_dictionary(
                dictionary.get("cover"))\
                if dictionary.get("cover") else None
        else:
            cover = APIHelper.SKIP
        public_url =\
            dictionary.get("public_url")\
            if "public_url" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(object,
                   id,
                   created_time,
                   last_edited_time,
                   created_by,
                   last_edited_by,
                   archived,
                   properties,
                   parent,
                   url,
                   in_trash,
                   icon,
                   cover,
                   public_url,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _object=self.object
        _id=self.id
        _created_time=self.created_time
        _last_edited_time=self.last_edited_time
        _created_by=self.created_by
        _last_edited_by=self.last_edited_by
        _archived=self.archived
        _in_trash=(
            self.in_trash
            if hasattr(self, "in_trash")
            else None
        )
        _icon=(
            self.icon
            if hasattr(self, "icon")
            else None
        )
        _cover=(
            self.cover
            if hasattr(self, "cover")
            else None
        )
        _properties=self.properties
        _parent=self.parent
        _url=self.url
        _public_url=(
            self.public_url
            if hasattr(self, "public_url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"object={_object!r}, "
            f"id={_id!r}, "
            f"created_time={_created_time!r}, "
            f"last_edited_time={_last_edited_time!r}, "
            f"created_by={_created_by!r}, "
            f"last_edited_by={_last_edited_by!r}, "
            f"archived={_archived!r}, "
            f"in_trash={_in_trash!r}, "
            f"icon={_icon!r}, "
            f"cover={_cover!r}, "
            f"properties={_properties!r}, "
            f"parent={_parent!r}, "
            f"url={_url!r}, "
            f"public_url={_public_url!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _object=self.object
        _id=self.id
        _created_time=self.created_time
        _last_edited_time=self.last_edited_time
        _created_by=self.created_by
        _last_edited_by=self.last_edited_by
        _archived=self.archived
        _in_trash=(
            self.in_trash
            if hasattr(self, "in_trash")
            else None
        )
        _icon=(
            self.icon
            if hasattr(self, "icon")
            else None
        )
        _cover=(
            self.cover
            if hasattr(self, "cover")
            else None
        )
        _properties=self.properties
        _parent=self.parent
        _url=self.url
        _public_url=(
            self.public_url
            if hasattr(self, "public_url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"object={_object!s}, "
            f"id={_id!s}, "
            f"created_time={_created_time!s}, "
            f"last_edited_time={_last_edited_time!s}, "
            f"created_by={_created_by!s}, "
            f"last_edited_by={_last_edited_by!s}, "
            f"archived={_archived!s}, "
            f"in_trash={_in_trash!s}, "
            f"icon={_icon!s}, "
            f"cover={_cover!s}, "
            f"properties={_properties!s}, "
            f"parent={_parent!s}, "
            f"url={_url!s}, "
            f"public_url={_public_url!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
