"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper
from notion.models.external_file import ExternalFile


class PagesRequest1(object):
    """Implementation of the 'Pages Request1' model.

    Attributes:
        properties (Any): Property values to update.
        archived (bool): Set to true to archive (trash) the page.
        icon (Emoji | ExternalFile | None): Page icon to set.
        cover (ExternalFile): Page cover image to set or remove.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "properties": "properties",
        "archived": "archived",
        "icon": "icon",
        "cover": "cover",
    }

    _optionals = [
        "properties",
        "archived",
        "icon",
        "cover",
    ]

    _nullables = [
        "icon",
        "cover",
    ]

    def __init__(
        self,
        properties=APIHelper.SKIP,
        archived=APIHelper.SKIP,
        icon=APIHelper.SKIP,
        cover=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PagesRequest1 instance."""
        # Initialize members of the class
        if properties is not APIHelper.SKIP:
            self.properties = properties
        if archived is not APIHelper.SKIP:
            self.archived = archived
        if icon is not APIHelper.SKIP:
            self.icon = icon
        if cover is not APIHelper.SKIP:
            self.cover = cover

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from notion.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        properties =\
            dictionary.get("properties")\
            if dictionary.get("properties")\
                else APIHelper.SKIP
        archived =\
            dictionary.get("archived")\
            if "archived" in dictionary.keys()\
                else APIHelper.SKIP
        if "icon" in dictionary.keys():
            icon = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("PagesRequest1Icon"),
            dictionary.get("icon"),
            False)\
            if dictionary.get("icon") is not None\
            else None
        else:
            icon = APIHelper.SKIP
        if "cover" in dictionary.keys():
            cover =\
                ExternalFile.from_dictionary(
                dictionary.get("cover"))\
                if dictionary.get("cover") else None
        else:
            cover = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(properties,
                   archived,
                   icon,
                   cover,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _properties=(
            self.properties
            if hasattr(self, "properties")
            else None
        )
        _archived=(
            self.archived
            if hasattr(self, "archived")
            else None
        )
        _icon=(
            self.icon
            if hasattr(self, "icon")
            else None
        )
        _cover=(
            self.cover
            if hasattr(self, "cover")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"properties={_properties!r}, "
            f"archived={_archived!r}, "
            f"icon={_icon!r}, "
            f"cover={_cover!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _properties=(
            self.properties
            if hasattr(self, "properties")
            else None
        )
        _archived=(
            self.archived
            if hasattr(self, "archived")
            else None
        )
        _icon=(
            self.icon
            if hasattr(self, "icon")
            else None
        )
        _cover=(
            self.cover
            if hasattr(self, "cover")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"properties={_properties!s}, "
            f"archived={_archived!s}, "
            f"icon={_icon!s}, "
            f"cover={_cover!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
