"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper
from notion.models.block import Block
from notion.models.external_file import ExternalFile
from notion.models.parent import Parent


class PagesRequest(object):
    """Implementation of the 'Pages Request' model.

    Attributes:
        parent (Parent): A Parent object represents the parent of a page, database,
            or block. The parent can be a workspace, page, database, or block.
        properties (Any): Property values for the new page. Keys are property names
            or IDs. If the parent is a database, the values must conform to the
            database schema.
        children (List[Block]): Page content as an array of block objects.
        icon (Emoji | ExternalFile | None): Page icon, either an emoji or external
            URL.
        cover (ExternalFile): Page cover image as an external URL.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "parent": "parent",
        "properties": "properties",
        "children": "children",
        "icon": "icon",
        "cover": "cover",
    }

    _optionals = [
        "children",
        "icon",
        "cover",
    ]

    def __init__(
        self,
        parent=None,
        properties=None,
        children=APIHelper.SKIP,
        icon=APIHelper.SKIP,
        cover=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PagesRequest instance."""
        # Initialize members of the class
        self.parent = parent
        self.properties = properties
        if children is not APIHelper.SKIP:
            self.children = children
        if icon is not APIHelper.SKIP:
            self.icon = icon
        if cover is not APIHelper.SKIP:
            self.cover = cover

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from notion.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        parent =\
            Parent.from_dictionary(
                dictionary.get("parent"))\
                if dictionary.get("parent") else None
        properties =\
            dictionary.get("properties")\
            if dictionary.get("properties")\
                else None
        children = None
        if dictionary.get("children") is not None:
            children = [
                Block.from_dictionary(x)
                    for x in dictionary.get("children")
            ]
        else:
            children = APIHelper.SKIP
        icon = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("PagesRequestIcon"),
            dictionary.get("icon"),
            False)\
            if dictionary.get("icon") is not None\
            else APIHelper.SKIP
        cover =\
            ExternalFile.from_dictionary(
                dictionary.get("cover"))\
                if "cover" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(parent,
                   properties,
                   children,
                   icon,
                   cover,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _parent=self.parent
        _properties=self.properties
        _children=(
            self.children
            if hasattr(self, "children")
            else None
        )
        _icon=(
            self.icon
            if hasattr(self, "icon")
            else None
        )
        _cover=(
            self.cover
            if hasattr(self, "cover")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"parent={_parent!r}, "
            f"properties={_properties!r}, "
            f"children={_children!r}, "
            f"icon={_icon!r}, "
            f"cover={_cover!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _parent=self.parent
        _properties=self.properties
        _children=(
            self.children
            if hasattr(self, "children")
            else None
        )
        _icon=(
            self.icon
            if hasattr(self, "icon")
            else None
        )
        _cover=(
            self.cover
            if hasattr(self, "cover")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"parent={_parent!s}, "
            f"properties={_properties!s}, "
            f"children={_children!s}, "
            f"icon={_icon!s}, "
            f"cover={_cover!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
