"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper


class PaginatedList(object):
    """Implementation of the 'PaginatedList' model.

    A paginated list of results returned by list and query endpoints. All paginated
    responses follow the same structure with a results array, pagination info, and
    object type.

    Attributes:
        object (Object): Always "list" for paginated responses.
        results (List[Any]): The array of result objects for the current page.
        next_cursor (str): The cursor to use for the next page of results, or null if
            there are no more results.
        has_more (bool): Whether there are more results available beyond this page.
        mtype (str): The type of objects in the results array.
        request_id (str): A unique identifier for this API request.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "object": "object",
        "results": "results",
        "next_cursor": "next_cursor",
        "has_more": "has_more",
        "mtype": "type",
        "request_id": "request_id",
    }

    _optionals = [
        "mtype",
        "request_id",
    ]

    _nullables = [
        "next_cursor",
    ]

    def __init__(
        self,
        object=None,
        results=None,
        next_cursor=None,
        has_more=None,
        mtype=APIHelper.SKIP,
        request_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PaginatedList instance."""
        # Initialize members of the class
        self.object = object
        self.results = results
        self.next_cursor = next_cursor
        self.has_more = has_more
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype
        if request_id is not APIHelper.SKIP:
            self.request_id = request_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        object =\
            dictionary.get("object")\
            if dictionary.get("object")\
                else None
        results =\
            dictionary.get("results")\
            if dictionary.get("results")\
                else None
        next_cursor =\
            dictionary.get("next_cursor")\
            if dictionary.get("next_cursor")\
                else None
        has_more =\
            dictionary.get("has_more")\
            if "has_more" in dictionary.keys()\
                else None
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP
        request_id =\
            dictionary.get("request_id")\
            if dictionary.get("request_id")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(object,
                   results,
                   next_cursor,
                   has_more,
                   mtype,
                   request_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _object=self.object
        _results=self.results
        _next_cursor=self.next_cursor
        _has_more=self.has_more
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"object={_object!r}, "
            f"results={_results!r}, "
            f"next_cursor={_next_cursor!r}, "
            f"has_more={_has_more!r}, "
            f"mtype={_mtype!r}, "
            f"request_id={_request_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _object=self.object
        _results=self.results
        _next_cursor=self.next_cursor
        _has_more=self.has_more
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"object={_object!s}, "
            f"results={_results!s}, "
            f"next_cursor={_next_cursor!s}, "
            f"has_more={_has_more!s}, "
            f"mtype={_mtype!s}, "
            f"request_id={_request_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
