"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper


class Parent11(object):
    """Implementation of the 'Parent11' model.

    The parent page to create the comment on. Required if discussion_id is not
    provided.

    Attributes:
        page_id (uuid|str): The ID of the parent page.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "page_id": "page_id",
    }

    _optionals = [
        "page_id",
    ]

    def __init__(
        self,
        page_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Parent11 instance."""
        # Initialize members of the class
        if page_id is not APIHelper.SKIP:
            self.page_id = page_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        page_id =\
            dictionary.get("page_id")\
            if dictionary.get("page_id")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(page_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _page_id=(
            self.page_id
            if hasattr(self, "page_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"page_id={_page_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _page_id=(
            self.page_id
            if hasattr(self, "page_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"page_id={_page_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
