"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper
from notion.models.mtype import Type


class Parent(object):
    """Implementation of the 'Parent' model.

    A Parent object represents the parent of a page, database, or block. The parent
    can be a workspace, page, database, or block.

    Attributes:
        mtype (Type): The type of parent.
        database_id (uuid|str): The ID of the parent database. Present when type is
            "database_id".
        page_id (uuid|str): The ID of the parent page. Present when type is "page_id".
        block_id (uuid|str): The ID of the parent block. Present when type is
            "block_id".
        workspace (bool): Always true when the parent is the workspace. Present when
            type is "workspace".
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": "type",
        "database_id": "database_id",
        "page_id": "page_id",
        "block_id": "block_id",
        "workspace": "workspace",
    }

    _optionals = [
        "database_id",
        "page_id",
        "block_id",
        "workspace",
    ]

    def __init__(
        self,
        mtype=None,
        database_id=APIHelper.SKIP,
        page_id=APIHelper.SKIP,
        block_id=APIHelper.SKIP,
        workspace=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Parent instance."""
        # Initialize members of the class
        self.mtype = mtype
        if database_id is not APIHelper.SKIP:
            self.database_id = database_id
        if page_id is not APIHelper.SKIP:
            self.page_id = page_id
        if block_id is not APIHelper.SKIP:
            self.block_id = block_id
        if workspace is not APIHelper.SKIP:
            self.workspace = workspace

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else None
        database_id =\
            dictionary.get("database_id")\
            if dictionary.get("database_id")\
                else APIHelper.SKIP
        page_id =\
            dictionary.get("page_id")\
            if dictionary.get("page_id")\
                else APIHelper.SKIP
        block_id =\
            dictionary.get("block_id")\
            if dictionary.get("block_id")\
                else APIHelper.SKIP
        workspace =\
            dictionary.get("workspace")\
            if "workspace" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(mtype,
                   database_id,
                   page_id,
                   block_id,
                   workspace,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.mtype,
                    type_callable=lambda value:
                        Type.validate(value))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("type"),
                type_callable=lambda value:
                    Type.validate(value))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mtype=self.mtype
        _database_id=(
            self.database_id
            if hasattr(self, "database_id")
            else None
        )
        _page_id=(
            self.page_id
            if hasattr(self, "page_id")
            else None
        )
        _block_id=(
            self.block_id
            if hasattr(self, "block_id")
            else None
        )
        _workspace=(
            self.workspace
            if hasattr(self, "workspace")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!r}, "
            f"database_id={_database_id!r}, "
            f"page_id={_page_id!r}, "
            f"block_id={_block_id!r}, "
            f"workspace={_workspace!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mtype=self.mtype
        _database_id=(
            self.database_id
            if hasattr(self, "database_id")
            else None
        )
        _page_id=(
            self.page_id
            if hasattr(self, "page_id")
            else None
        )
        _block_id=(
            self.block_id
            if hasattr(self, "block_id")
            else None
        )
        _workspace=(
            self.workspace
            if hasattr(self, "workspace")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!s}, "
            f"database_id={_database_id!s}, "
            f"page_id={_page_id!s}, "
            f"block_id={_block_id!s}, "
            f"workspace={_workspace!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
