"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper


class Parent1(object):
    """Implementation of the 'Parent1' model.

    The parent page or block the comment belongs to.

    Attributes:
        mtype (Type11): The model property of type Type11.
        page_id (uuid|str): The model property of type uuid|str.
        block_id (uuid|str): The model property of type uuid|str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": "type",
        "page_id": "page_id",
        "block_id": "block_id",
    }

    _optionals = [
        "mtype",
        "page_id",
        "block_id",
    ]

    def __init__(
        self,
        mtype=APIHelper.SKIP,
        page_id=APIHelper.SKIP,
        block_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Parent1 instance."""
        # Initialize members of the class
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype
        if page_id is not APIHelper.SKIP:
            self.page_id = page_id
        if block_id is not APIHelper.SKIP:
            self.block_id = block_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP
        page_id =\
            dictionary.get("page_id")\
            if dictionary.get("page_id")\
                else APIHelper.SKIP
        block_id =\
            dictionary.get("block_id")\
            if dictionary.get("block_id")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(mtype,
                   page_id,
                   block_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _page_id=(
            self.page_id
            if hasattr(self, "page_id")
            else None
        )
        _block_id=(
            self.block_id
            if hasattr(self, "block_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!r}, "
            f"page_id={_page_id!r}, "
            f"block_id={_block_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _page_id=(
            self.page_id
            if hasattr(self, "page_id")
            else None
        )
        _block_id=(
            self.block_id
            if hasattr(self, "block_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!s}, "
            f"page_id={_page_id!s}, "
            f"block_id={_block_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
