"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper
from notion.models.annotations import Annotations
from notion.models.equation import Equation
from notion.models.text import Text
from notion.models.type_2 import Type2


class RichText(object):
    """Implementation of the 'RichText' model.

    A Rich Text object represents styled text content in Notion. Rich text can
    include annotations like bold, italic, and color, as well as links and mentions
    of other Notion objects.

    Attributes:
        mtype (Type2): The type of this rich text object.
        text (Text): Text content and optional link. Present when type is "text".
        mention (Any): Mention content. Present when type is "mention". Can reference
            users, pages, databases, dates, or link previews.
        equation (Equation): Equation content in KaTeX format. Present when type is
            "equation".
        annotations (Annotations): Styling annotations applied to the text.
        plain_text (str): The plain text content without annotations.
        href (str): The URL of any link in the text, or null.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": "type",
        "plain_text": "plain_text",
        "text": "text",
        "mention": "mention",
        "equation": "equation",
        "annotations": "annotations",
        "href": "href",
    }

    _optionals = [
        "text",
        "mention",
        "equation",
        "annotations",
        "href",
    ]

    _nullables = [
        "href",
    ]

    def __init__(
        self,
        mtype=None,
        plain_text=None,
        text=APIHelper.SKIP,
        mention=APIHelper.SKIP,
        equation=APIHelper.SKIP,
        annotations=APIHelper.SKIP,
        href=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a RichText instance."""
        # Initialize members of the class
        self.mtype = mtype
        if text is not APIHelper.SKIP:
            self.text = text
        if mention is not APIHelper.SKIP:
            self.mention = mention
        if equation is not APIHelper.SKIP:
            self.equation = equation
        if annotations is not APIHelper.SKIP:
            self.annotations = annotations
        self.plain_text = plain_text
        if href is not APIHelper.SKIP:
            self.href = href

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else None
        plain_text =\
            dictionary.get("plain_text")\
            if dictionary.get("plain_text")\
                else None
        text =\
            Text.from_dictionary(
                dictionary.get("text"))\
                if "text" in dictionary.keys()\
                else APIHelper.SKIP
        mention =\
            dictionary.get("mention")\
            if dictionary.get("mention")\
                else APIHelper.SKIP
        equation =\
            Equation.from_dictionary(
                dictionary.get("equation"))\
                if "equation" in dictionary.keys()\
                else APIHelper.SKIP
        annotations =\
            Annotations.from_dictionary(
                dictionary.get("annotations"))\
                if "annotations" in dictionary.keys()\
                else APIHelper.SKIP
        href =\
            dictionary.get("href")\
            if "href" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(mtype,
                   plain_text,
                   text,
                   mention,
                   equation,
                   annotations,
                   href,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.mtype,
                    type_callable=lambda value:
                        Type2.validate(value)) \
                and APIHelper.is_valid_type(
                    value=dictionary.plain_text,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("type"),
                type_callable=lambda value:
                    Type2.validate(value)) \
            and APIHelper.is_valid_type(
                value=dictionary.get("plain_text"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mtype=self.mtype
        _text=(
            self.text
            if hasattr(self, "text")
            else None
        )
        _mention=(
            self.mention
            if hasattr(self, "mention")
            else None
        )
        _equation=(
            self.equation
            if hasattr(self, "equation")
            else None
        )
        _annotations=(
            self.annotations
            if hasattr(self, "annotations")
            else None
        )
        _plain_text=self.plain_text
        _href=(
            self.href
            if hasattr(self, "href")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!r}, "
            f"text={_text!r}, "
            f"mention={_mention!r}, "
            f"equation={_equation!r}, "
            f"annotations={_annotations!r}, "
            f"plain_text={_plain_text!r}, "
            f"href={_href!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mtype=self.mtype
        _text=(
            self.text
            if hasattr(self, "text")
            else None
        )
        _mention=(
            self.mention
            if hasattr(self, "mention")
            else None
        )
        _equation=(
            self.equation
            if hasattr(self, "equation")
            else None
        )
        _annotations=(
            self.annotations
            if hasattr(self, "annotations")
            else None
        )
        _plain_text=self.plain_text
        _href=(
            self.href
            if hasattr(self, "href")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!s}, "
            f"text={_text!s}, "
            f"mention={_mention!s}, "
            f"equation={_equation!s}, "
            f"annotations={_annotations!s}, "
            f"plain_text={_plain_text!s}, "
            f"href={_href!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
