"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper
from notion.models.filter import Filter
from notion.models.sort_1 import Sort1


class SearchRequest(object):
    """Implementation of the 'Search Request' model.

    Attributes:
        query (str): The text to search for in page and database titles. If omitted,
            returns all pages and databases.
        filter (Filter): Filter conditions. Currently only supports filtering by
            object type (page or database).
        sort (Sort1): Sort conditions for the results.
        start_cursor (str): Pagination cursor to continue fetching results.
        page_size (int): Maximum number of results to return (max 100).
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "query": "query",
        "filter": "filter",
        "sort": "sort",
        "start_cursor": "start_cursor",
        "page_size": "page_size",
    }

    _optionals = [
        "query",
        "filter",
        "sort",
        "start_cursor",
        "page_size",
    ]

    def __init__(
        self,
        query=APIHelper.SKIP,
        filter=APIHelper.SKIP,
        sort=APIHelper.SKIP,
        start_cursor=APIHelper.SKIP,
        page_size=100,
        additional_properties=None):
        """Initialize a SearchRequest instance."""
        # Initialize members of the class
        if query is not APIHelper.SKIP:
            self.query = query
        if filter is not APIHelper.SKIP:
            self.filter = filter
        if sort is not APIHelper.SKIP:
            self.sort = sort
        if start_cursor is not APIHelper.SKIP:
            self.start_cursor = start_cursor
        self.page_size = page_size

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        query =\
            dictionary.get("query")\
            if dictionary.get("query")\
                else APIHelper.SKIP
        filter =\
            Filter.from_dictionary(
                dictionary.get("filter"))\
                if "filter" in dictionary.keys()\
                else APIHelper.SKIP
        sort =\
            Sort1.from_dictionary(
                dictionary.get("sort"))\
                if "sort" in dictionary.keys()\
                else APIHelper.SKIP
        start_cursor =\
            dictionary.get("start_cursor")\
            if dictionary.get("start_cursor")\
                else APIHelper.SKIP
        page_size =\
            dictionary.get("page_size")\
            if dictionary.get("page_size")\
                else 100

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(query,
                   filter,
                   sort,
                   start_cursor,
                   page_size,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _query=(
            self.query
            if hasattr(self, "query")
            else None
        )
        _filter=(
            self.filter
            if hasattr(self, "filter")
            else None
        )
        _sort=(
            self.sort
            if hasattr(self, "sort")
            else None
        )
        _start_cursor=(
            self.start_cursor
            if hasattr(self, "start_cursor")
            else None
        )
        _page_size=(
            self.page_size
            if hasattr(self, "page_size")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"query={_query!r}, "
            f"filter={_filter!r}, "
            f"sort={_sort!r}, "
            f"start_cursor={_start_cursor!r}, "
            f"page_size={_page_size!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _query=(
            self.query
            if hasattr(self, "query")
            else None
        )
        _filter=(
            self.filter
            if hasattr(self, "filter")
            else None
        )
        _sort=(
            self.sort
            if hasattr(self, "sort")
            else None
        )
        _start_cursor=(
            self.start_cursor
            if hasattr(self, "start_cursor")
            else None
        )
        _page_size=(
            self.page_size
            if hasattr(self, "page_size")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"query={_query!s}, "
            f"filter={_filter!s}, "
            f"sort={_sort!s}, "
            f"start_cursor={_start_cursor!s}, "
            f"page_size={_page_size!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
