"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper


class Sort1(object):
    """Implementation of the 'Sort1' model.

    Sort conditions for the results.

    Attributes:
        direction (Direction): The sort direction.
        timestamp (Timestamp1): The timestamp to sort by.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "direction": "direction",
        "timestamp": "timestamp",
    }

    _optionals = [
        "direction",
        "timestamp",
    ]

    def __init__(
        self,
        direction=APIHelper.SKIP,
        timestamp=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Sort1 instance."""
        # Initialize members of the class
        if direction is not APIHelper.SKIP:
            self.direction = direction
        if timestamp is not APIHelper.SKIP:
            self.timestamp = timestamp

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        direction =\
            dictionary.get("direction")\
            if dictionary.get("direction")\
                else APIHelper.SKIP
        timestamp =\
            dictionary.get("timestamp")\
            if dictionary.get("timestamp")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(direction,
                   timestamp,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _direction=(
            self.direction
            if hasattr(self, "direction")
            else None
        )
        _timestamp=(
            self.timestamp
            if hasattr(self, "timestamp")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"direction={_direction!r}, "
            f"timestamp={_timestamp!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _direction=(
            self.direction
            if hasattr(self, "direction")
            else None
        )
        _timestamp=(
            self.timestamp
            if hasattr(self, "timestamp")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"direction={_direction!s}, "
            f"timestamp={_timestamp!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
