"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper
from notion.models.link import Link


class Text(object):
    """Implementation of the 'Text' model.

    Text content and optional link. Present when type is "text".

    Attributes:
        content (str): The actual text content.
        link (Link): Optional link within the text.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "content": "content",
        "link": "link",
    }

    _optionals = [
        "content",
        "link",
    ]

    _nullables = [
        "link",
    ]

    def __init__(
        self,
        content=APIHelper.SKIP,
        link=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Text instance."""
        # Initialize members of the class
        if content is not APIHelper.SKIP:
            self.content = content
        if link is not APIHelper.SKIP:
            self.link = link

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        content =\
            dictionary.get("content")\
            if dictionary.get("content")\
                else APIHelper.SKIP
        if "link" in dictionary.keys():
            link =\
                Link.from_dictionary(
                dictionary.get("link"))\
                if dictionary.get("link") else None
        else:
            link = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(content,
                   link,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _content=(
            self.content
            if hasattr(self, "content")
            else None
        )
        _link=(
            self.link
            if hasattr(self, "link")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"content={_content!r}, "
            f"link={_link!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _content=(
            self.content
            if hasattr(self, "content")
            else None
        )
        _link=(
            self.link
            if hasattr(self, "link")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"content={_content!s}, "
            f"link={_link!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
