"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Type31(object):
    """Implementation of the 'Type31' enum.

    The type of property.

    Attributes:
        TITLE: The enum member of type str.
        RICH_TEXT: The enum member of type str.
        NUMBER: The enum member of type str.
        SELECT: The enum member of type str.
        MULTI_SELECT: The enum member of type str.
        DATE: The enum member of type str.
        PEOPLE: The enum member of type str.
        FILES: The enum member of type str.
        CHECKBOX: The enum member of type str.
        URL: The enum member of type str.
        EMAIL: The enum member of type str.
        PHONE_NUMBER: The enum member of type str.
        FORMULA: The enum member of type str.
        RELATION: The enum member of type str.
        ROLLUP: The enum member of type str.
        CREATED_TIME: The enum member of type str.
        CREATED_BY: The enum member of type str.
        LAST_EDITED_TIME: The enum member of type str.
        LAST_EDITED_BY: The enum member of type str.
        STATUS: The enum member of type str.
        UNIQUE_ID: The enum member of type str.
        VERIFICATION: The enum member of type str.

    """

    _all_values = ["title", "rich_text", "number", "select", "multi_select", "date", "people",
        "files", "checkbox", "url", "email", "phone_number", "formula", "relation",
        "rollup", "created_time", "created_by", "last_edited_time", "last_edited_by",
        "status", "unique_id", "verification"]
    TITLE = "title"

    RICH_TEXT = "rich_text"

    NUMBER = "number"

    SELECT = "select"

    MULTI_SELECT = "multi_select"

    DATE = "date"

    PEOPLE = "people"

    FILES = "files"

    CHECKBOX = "checkbox"

    URL = "url"

    EMAIL = "email"

    PHONE_NUMBER = "phone_number"

    FORMULA = "formula"

    RELATION = "relation"

    ROLLUP = "rollup"

    CREATED_TIME = "created_time"

    CREATED_BY = "created_by"

    LAST_EDITED_TIME = "last_edited_time"

    LAST_EDITED_BY = "last_edited_by"

    STATUS = "status"

    UNIQUE_ID = "unique_id"

    VERIFICATION = "verification"

    @classmethod
    def validate(cls, value):
        """Validate value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
