"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Type1(object):
    """Implementation of the 'Type1' enum.

    The type of block. Determines which type-specific content field is present.
    Common types include paragraph, heading_1, heading_2, heading_3,
    bulleted_list_item, numbered_list_item, to_do, toggle, code, image, divider,
    table, and many more.

    Attributes:
        PARAGRAPH: The enum member of type str.
        HEADING_1: The enum member of type str.
        HEADING_2: The enum member of type str.
        HEADING_3: The enum member of type str.
        BULLETED_LIST_ITEM: The enum member of type str.
        NUMBERED_LIST_ITEM: The enum member of type str.
        TO_DO: The enum member of type str.
        TOGGLE: The enum member of type str.
        CHILD_PAGE: The enum member of type str.
        CHILD_DATABASE: The enum member of type str.
        EMBED: The enum member of type str.
        IMAGE: The enum member of type str.
        VIDEO: The enum member of type str.
        FILE: The enum member of type str.
        PDF: The enum member of type str.
        BOOKMARK: The enum member of type str.
        CALLOUT: The enum member of type str.
        QUOTE: The enum member of type str.
        EQUATION: The enum member of type str.
        DIVIDER: The enum member of type str.
        TABLE_OF_CONTENTS: The enum member of type str.
        COLUMN_LIST: The enum member of type str.
        COLUMN: The enum member of type str.
        LINK_PREVIEW: The enum member of type str.
        SYNCED_BLOCK: The enum member of type str.
        TEMPLATE: The enum member of type str.
        LINK_TO_PAGE: The enum member of type str.
        TABLE: The enum member of type str.
        TABLE_ROW: The enum member of type str.
        CODE: The enum member of type str.
        AUDIO: The enum member of type str.
        BREADCRUMB: The enum member of type str.

    """

    _all_values = ["paragraph", "heading_1", "heading_2", "heading_3", "bulleted_list_item",
        "numbered_list_item", "to_do", "toggle", "child_page", "child_database",
        "embed", "image", "video", "file", "pdf", "bookmark", "callout", "quote",
        "equation", "divider", "table_of_contents", "column_list", "column",
        "link_preview", "synced_block", "template", "link_to_page", "table",
        "table_row", "code", "audio", "breadcrumb"]
    PARAGRAPH = "paragraph"

    HEADING_1 = "heading_1"

    HEADING_2 = "heading_2"

    HEADING_3 = "heading_3"

    BULLETED_LIST_ITEM = "bulleted_list_item"

    NUMBERED_LIST_ITEM = "numbered_list_item"

    TO_DO = "to_do"

    TOGGLE = "toggle"

    CHILD_PAGE = "child_page"

    CHILD_DATABASE = "child_database"

    EMBED = "embed"

    IMAGE = "image"

    VIDEO = "video"

    FILE = "file"

    PDF = "pdf"

    BOOKMARK = "bookmark"

    CALLOUT = "callout"

    QUOTE = "quote"

    EQUATION = "equation"

    DIVIDER = "divider"

    TABLE_OF_CONTENTS = "table_of_contents"

    COLUMN_LIST = "column_list"

    COLUMN = "column"

    LINK_PREVIEW = "link_preview"

    SYNCED_BLOCK = "synced_block"

    TEMPLATE = "template"

    LINK_TO_PAGE = "link_to_page"

    TABLE = "table"

    TABLE_ROW = "table_row"

    CODE = "code"

    AUDIO = "audio"

    BREADCRUMB = "breadcrumb"

    @classmethod
    def validate(cls, value):
        """Validate value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
