"""notion.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from notion.api_helper import APIHelper
from notion.models.bot import Bot
from notion.models.person import Person


class User(object):
    """Implementation of the 'User' model.

    A User object represents a user in a Notion workspace. Users can be either people
    (human workspace members) or bots (API integrations). User objects include
    identifying information such as name, email, and avatar URL.

    Attributes:
        object (Object2): Always "user" for user objects.
        id (uuid|str): Unique identifier for the user.
        mtype (Type4): The type of user. "person" for human workspace members, "bot"
            for API integrations.
        name (str): Display name of the user.
        avatar_url (str): URL of the user's avatar image.
        person (Person): Person-specific information. Only present when type is
            "person".
        bot (Bot): Bot-specific information. Only present when type is "bot".
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "object": "object",
        "id": "id",
        "mtype": "type",
        "name": "name",
        "avatar_url": "avatar_url",
        "person": "person",
        "bot": "bot",
    }

    _optionals = [
        "mtype",
        "name",
        "avatar_url",
        "person",
        "bot",
    ]

    _nullables = [
        "name",
        "avatar_url",
    ]

    def __init__(
        self,
        object=None,
        id=None,
        mtype=APIHelper.SKIP,
        name=APIHelper.SKIP,
        avatar_url=APIHelper.SKIP,
        person=APIHelper.SKIP,
        bot=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a User instance."""
        # Initialize members of the class
        self.object = object
        self.id = id
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype
        if name is not APIHelper.SKIP:
            self.name = name
        if avatar_url is not APIHelper.SKIP:
            self.avatar_url = avatar_url
        if person is not APIHelper.SKIP:
            self.person = person
        if bot is not APIHelper.SKIP:
            self.bot = bot

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        object =\
            dictionary.get("object")\
            if dictionary.get("object")\
                else None
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if "name" in dictionary.keys()\
                else APIHelper.SKIP
        avatar_url =\
            dictionary.get("avatar_url")\
            if "avatar_url" in dictionary.keys()\
                else APIHelper.SKIP
        person =\
            Person.from_dictionary(
                dictionary.get("person"))\
                if "person" in dictionary.keys()\
                else APIHelper.SKIP
        bot =\
            Bot.from_dictionary(
                dictionary.get("bot"))\
                if "bot" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(object,
                   id,
                   mtype,
                   name,
                   avatar_url,
                   person,
                   bot,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _object=self.object
        _id=self.id
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _avatar_url=(
            self.avatar_url
            if hasattr(self, "avatar_url")
            else None
        )
        _person=(
            self.person
            if hasattr(self, "person")
            else None
        )
        _bot=(
            self.bot
            if hasattr(self, "bot")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"object={_object!r}, "
            f"id={_id!r}, "
            f"mtype={_mtype!r}, "
            f"name={_name!r}, "
            f"avatar_url={_avatar_url!r}, "
            f"person={_person!r}, "
            f"bot={_bot!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _object=self.object
        _id=self.id
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _avatar_url=(
            self.avatar_url
            if hasattr(self, "avatar_url")
            else None
        )
        _person=(
            self.person
            if hasattr(self, "person")
            else None
        )
        _bot=(
            self.bot
            if hasattr(self, "bot")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"object={_object!s}, "
            f"id={_id!s}, "
            f"mtype={_mtype!s}, "
            f"name={_name!s}, "
            f"avatar_url={_avatar_url!s}, "
            f"person={_person!s}, "
            f"bot={_bot!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
